# Generated by Django 4.0.3 on 2022-03-19 12:47

import basedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('slug', models.CharField(default=basedata.models.get_slug, max_length=255, primary_key=True, serialize=False)),
                ('active', models.CharField(default='YES', max_length=20)),
                ('grade', models.CharField(choices=[('FORM 1', 'FORM 1'), ('FORM 2', 'FORM 2'), ('FORM 3', 'FORM 3'), ('FORM 4', 'FORM 4'), ('FORM 5', 'FORM 5'), ('FORM 6', 'FORM 6')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
