# Generated by Django 4.0.3 on 2022-03-19 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 19, 13, 11, 36, 420201, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
