# Generated by Django 4.0.3 on 2022-03-19 13:43

import basedata.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleManufacturer',
            fields=[
                ('slug', models.CharField(default=basedata.models.get_slug, max_length=255, primary_key=True, serialize=False)),
                ('active', models.CharField(default='YES', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('slug', models.CharField(default=basedata.models.get_slug, max_length=255, primary_key=True, serialize=False)),
                ('active', models.CharField(default='YES', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('school_tag', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bicycles', to='bicycle.bicyclemanufacturer')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bicycle', to='users.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
